stages:
  - build

build:
  stage: build
  image: maven:3-jdk-17
  script:
    - mvn spring-boot:build-image -e -DGOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
  artifacts:
    paths:
      - target/*.jar
  only:
    - tags