version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  app-net:
    driver: overlay

volumes:
  app-data:
    driver: local